import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 3.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets build hulu</h1>

      {/* Header */}

      {/* Nav */}
    
      {/* Results */}
    </div>
  )
}
